#INCLUDE "PROTHEUS.CH"

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma ณF200PORT บAutor ณRoseclei Ventura 28/11/2023
ออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDesc. ณ Ponto de entrada que com retorno T/F se a baixa serแ pelo
portador do Titulo ou pelo parametro
ฑฑบ ณ บฑฑ
ฑฑฬออออออออออุออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออนฑฑ
O que este ponto de entrada faz ้ na verdade retornar .T. se o retorno deverแ 
considerar a conta para baixa do titulo a mesma enviada no bordero de cobran็a,
 ou seja, E1_PORTADO, E1_AGEDEP e E1_CONTA, ou .F. se a conta informada
 no parโmetro da tela de retorno cnab.
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User Function F200PORT()
   Local lRet := .T.

   If AllTrim(cBanco) == '637' .OR. AllTrim(cBanco) == '033' .OR. AllTrim(cBanco) == '001'
      lRet := .F.
   Endif

   Return lRet

/*
User Function F200PORT()
Local lRet := .T.

If AllTrim(cBanco) == '637' // Se For Banco Santander Entใo Nใo Considera o E1_PORTADO Considera o Banco Informado nos Parโmetros
lRet := .F.
Endif */

Return lRet

